name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  linter:
    name: Linters
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18
    
    - name: Lint with ESlint
      run: npm run lint
    
  test:
    name: Test Chunker
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18
    
    - name: Install Dependencies
      run: npm ci
    
    - name: Test Chunker
      run: npm run test